[package]
name = "rect-dominance"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rect-core = { path = "../rect-core" }
rect-graph = { path = "../rect-graph" }
rect-oracle-sg = { path = "../rect-oracle-sg" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true

